version: '2'

services:
  redis:
    image: 'redis'
    command: redis-server
    volumes:
      - 'redis:/data'
  web:
    build: .
    volumes:
      - .:/mailer
    links:
      - redis
    ports:
      - "3001:3001"
    command: bash -c "bundle install && bundle exec rails server -b 0.0.0.0 -p 3001"
  sidekiq1:
    depends_on:
      - 'redis'
    build: .
    command: bash -c "bundle install && bundle exec sidekiq"
    volumes:
      - '.:/mailer'
  sidekiq2:
    depends_on:
      - 'redis'
    build: .
    command: bash -c "bundle install && bundle exec sidekiq"
    volumes:
      - '.:/mailer'

volumes:
  redis: